version: "3.8"

services:
  app:
    build:
      context: ./blog
      dockerfile: ../Dockerfile
    volumes:
      - ./blog:/app
      # ローカルの../front/bookers2-frontをコンテナ内の/appにまうんと
      # - front_node_modules:/app/node_modules
    ports:
      - "3000:3000"
